# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false

    runs-on: ${{ matrix.os }}

    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (latest 3.12)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (latest 3.12)
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade black pyright pytest pytest-cov

      - name: Format with black (latest 3.12)
        run: |
          black --diff .

      - name: Lint with pyright (latest 3.12)
        run: |
          pyright

      - name: Test with pytest (latest 3.12)
        run: |
          pytest --cov --cov-report=xml --cov-append

      - name: Set up Python (3.12.0)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.0"

      - name: Install dependencies (3.12.0)
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest pytest-cov

      - name: Test with pytest (3.12.0)
        run: |
          pytest --cov --cov-report=xml --cov-append

      - name: Set up latest Python (latest 3.11)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (latest 3.11)
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest pytest-cov

      - name: Test with pytest (latest 3.11)
        run: |
          pytest --cov --cov-report=xml --cov-append

      - name: Set up Python 3.11.0 (3.11.0)
        if: ${{ ! startsWith(matrix.os, "macos") }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.0"

      - name: Install dependencies (3.11.0)
        if: ${{ ! startsWith(matrix.os, "macos") }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest pytest-cov

      - name: Test with pytest (3.11.0)
        if: ${{ ! startsWith(matrix.os, "macos") }}
        run: |
          pytest --cov --cov-report=xml --cov-append

      - name: Coveralls      
        uses: coverallsapp/github-action@v2.3.0          
